server:
  port: 8083
  servlet:
    contextPath: /cashier

account:
  getEndpoint: http://localhost:8082/account/search/{accountNumber}

kafka:
  bootstrapAddress: http://localhost:9092
  topicName: transaction